In [70]:
import numpy as np

In [71]:
m = 5
n = 3

w = np.random.rand(m, 1)
X = np.random.rand(m, n)
Y = np.random.rand(m, n)
b = np.random.uniform()
alpha = np.random.uniform()

print('w:')
print(w)
print('X:')
print(X)
print('Y:')
print(Y)
print('b:')
print(b)
print('alpha:')
print(alpha)

w:
[[0.21228316]
 [0.06644906]
 [0.63232486]
 [0.19924107]
 [0.92800724]]
X:
[[0.68314092 0.57993587 0.56146906]
 [0.9650968  0.00791482 0.682249  ]
 [0.87119158 0.0922937  0.25213637]
 [0.58890927 0.1183673  0.41130379]
 [0.88285257 0.89159301 0.21087904]]
Y:
[[0.14111329 0.97288034 0.79002918]
 [0.49385215 0.43457377 0.91527805]
 [0.93302709 0.40465276 0.51514005]
 [0.9819966  0.32385096 0.72449598]
 [0.99068999 0.18458478 0.35852387]]
b:
0.7339995280392968
alpha:
0.8770759135024211


In [72]:
Z = np.dot(np.transpose(w), X) + b

print(Z)

[[2.4306532  1.76698408 1.33560274]]


In [73]:
def sigmoid(X):
   return 1/(1+np.exp(-X))

In [74]:
A = sigmoid(Z)

print(A)

[[0.9191351  0.85408221 0.79176588]]


In [75]:
dZ = A - Y

print(dZ)

[[ 0.7780218  -0.11879813  0.00173671]
 [ 0.42528295  0.41950844 -0.12351217]
 [-0.01389199  0.44942945  0.27662583]
 [-0.0628615   0.53023125  0.0672699 ]
 [-0.07155489  0.66949743  0.43324201]]


In [76]:
dw = 1/m * sum(X * dZ)

print(dw)

[0.1659286  0.12711716 0.0210973 ]


In [77]:
db = 1/m * np.sum(dZ)

print(db)

0.7320454192537316


In [78]:
w = w - alpha * dw
b = b - alpha * db

print(w)
print(b)

[[ 0.06675118  0.10079176  0.19377922]
 [-0.07908292 -0.04504234  0.04794513]
 [ 0.48679288  0.52083346  0.61382093]
 [ 0.05370909  0.08774967  0.18073714]
 [ 0.78247526  0.81651584  0.9095033 ]]
0.09194012322206735
